---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/networking.k8s.io/networkpolicy_v1.json
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kritika-same-node-replies
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: kritika
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              cnpg.io/cluster: kritika-postgres
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: kritika
